name: sesame-tts
category: audio
description: Sesame CSM text-to-speech for Jetson
version: 1.0
license: MIT
docs: docs.md
maintainer: Kieran
requires:
  - cuda
  - ">=jp6.1"
  - "==aarch64"
depends:
  - python
  - pytorch
build_args:
  BASE_IMAGE: dustynv/pytorch:2.6-r36.4.0-cu128-24.04
  JETPACK_VERSION: 6.1
  CUDA_VERSION: 12.8
test_script: test.sh
run_script: run.sh
